apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-ebs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: roboshop-ebs

---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html-data
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  volumes:
    - name: html-data
      persistentVolumeClaim:
        claimName: dynamic-ebs
