apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: roboshop-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0f0d6c6ae7e4fb30a
  directoryPerms: "700"
  basePath: "/roboshop"
reclaimPolicy: Retain
