apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  labels:
    project: roboshop
    environment: dev
    purpose: poc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
    kubernetes.io/change-cause: "Updated nginx image to 1.25"
spec:
  containers:
    - name: nginx
      image: nginx
