apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: roboshop-dev
  region: us-east-1

managedNodeGroups:
  - name: roboshop-dev-managed
    instanceTypes:
      [
        "t3.medium",
        "t3a.medium",
        "m5.large",
        "m5a.large",
        "c5.large",
        "c5a.large",
      ]
    spot: true
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
